apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudflared
  namespace: misskey
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloudflared
  template:
    metadata:
      labels:
        app: cloudflared
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
                - key: kubernetes.io/hostname
                  operator: In
                  values:
                    - pi41
      containers:
      - name: cloudflared
        image: cloudflare/cloudflared
        command:
          - cloudflared
          - tunnel
          - run
        envFrom:
        - secretRef:
            name: misskey-secret
